language: objective-c
osx_image: xcode10
# xcode_project: Enveloppe.xcodeproj
# xcode_scheme: Tests
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

script:
  - xcodebuild test -project Enveloppe.xcodeproj -scheme Enveloppe -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,OS=12.0,name=iPhone X"
  - xctool -project Enveloppe.xcodeproj -scheme Enveloppe -sdk iphonesimulator run-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
